### ISSUE TITLE
ssl client cert ?

### ISSUE THREAD

**Issue by momiji** [jrwesolo/yumsync#22]
Hello,

I was looking at this very intersting projet, but could not get sslclientcert, key and cacert working.
I patched the self.__repo_obj to add these values from the opts dict, and configured them in the yaml file, but it still does not work.

Any idea to help me? Maybe am I missing another option in YumBase?

I'll be happy to share a PR once I got it working :)

Regards

**Comment by jrwesolo** [comment]
I'd be happy to check into this for you! Do you have an example repo that uses self-signed certs that you can provide me or are you testing this on an internal repo (e.g. company repo)? If you can provide that it will help me test easier. Otherwise, I'll need to stand up my own repo for testing.

**Comment by momiji** [comment]
Thank's  a lot.

Unfortunately, the repo that use certificates are redhat ones.

I'm proxying all the repo we are using as our servers do not have access to internet, and versionning is also definitely a must have for us. The only repo that requires certificates are the redhat ones, I'm not aware of any other repo like this.

Also I'm not sure whether the certs I give are really good, as I couldn't get curl with --key and --cert working. Maybe I missed something else that is not related to YumBase, I'll try to investigate in this direction at the same time.

They are both in PEM format, well I believe so.
* The cert contains `CERTIFICATE`, `ENTITLEMENT DATA` and `RSA SIGNATURE`.
* The key contains only `RSA PRIVATE KEY`.

The lines I've added in yumrepo.py are:
```
         self.stable = opts['stable']
         self.version = time.strftime(opts['version']) if opts['version'] else None
         self.srcpkgs = opts['srcpkgs']
+        self.__repo_obj.sslverify = opts['sslverify']
+        self.__repo_obj.sslclientcert = opts['sslclientcert']
+        self.__repo_obj.sslclientkey = opts['sslclientkey']
+        self.__repo_obj.sslcacert = opts['sslcacert']

         # root directory for repo and packages
         self.dir = os.path.join(base_dir, self._friendly(self.id))
```

I'll be waiting for your feedback.

**Comment by lkeijser** [comment]
I'm facing the same issue (unable to sync a RHEL repo). Is there any progress on this?

**Comment by momiji** [comment]
Hi, the good news is that... the problem was coming from my certificates, that were not valid anymore.

Now that I understand better how it works, `openssl x509 -in cert.pem -text -noout` displays that it expired in january ;-( Sorry...

Now that curl is working again, I'll be able to see if my changes are working or not. I'll keep you informed when done.

**Comment by momiji** [comment]
OK, I found my old working dir with the modified python project, and I confirm it now works.
All was my fault, I'm really really sorry.
Thanks.

if @lkeijser is ok, you can close this issue.
